### ISSUE TITLE
Can't authorize GMail

### ISSUE THREAD

**Issue by foucdeg** [theodo/scrumble#113]
As I'm about to send a daily mail using Scrumble (never done it before), I click on "Authorize GMail", I get to the Google Accounts page where I choose my Theodo UK account.
Then I am taken back to Scrumble, but the Send button is still disabled and the Authorize GMail button is still enabled.

**Comment by nicgirault** [comment]
@foucdeg thank you for reporting this issue. You're not the first one to get an issue about this behavior. I guess there are 2 concurrent job running à the same time after the oauth popup redirect to the app:
- the authorization service that try to get the gmail token from the URL
- the angular redirection that removes the token from the URL

If the second one is faster than the first one, it does not work... If you try several time it should eventually work.

I'll try to fix this issue.

**Comment by nicgirault** [comment]
This will be fix when the loopback API will be oneline (a backend route is required)
