### ISSUE TITLE
I miss Scrumble :'(

### ISSUE THREAD

**Issue by CyrilleHugues** [theodo/scrumble#116]
Thanks for providing this awesome tool !

This url throws a `504` error :
`https://api.parse.com/1/classes/Sprint?where=%7B%22project%22:%7B%22__type%22:%22Pointer%22,%22className%22:%22Project%22,%22objectId%22:%22rb3LJf13wQ%22%7D,%22isActive%22:true%7D`

```
No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://theodo.github.io' is therefore not allowed access. The response had HTTP status code 504.
```

**Comment by nicgirault** [comment]
@CyrilleHugues sorry for the response time. Is it still an issue? Sometime parse is down... It looks like this was your problem
