### ISSUE TITLE
[daily mail] Smiling smiley =) in case of lateness :(

### ISSUE THREAD

**Issue by HugoCapocci** [theodo/scrumble#118]
The smiley on the down burn chart seems to be right, _sad_ in case of lateness, _happy_ when everything's fine.
But the one on the daily mail, on the "lateness" line (see screenshot below) is smiling when sprint is late..  it's not a big deal but something to be fixed anyway ;)

![image](https://cloud.githubusercontent.com/assets/2291654/15213474/ca5397da-1847-11e6-84de-ba21e9b0924c.png)

**Comment by nicgirault** [comment]
This is in your report template!

**Comment by nicgirault** [comment]
Can you close the issue if it's ok?

**Comment by HugoCapocci** [comment]
@nicgirault sure, my bad ;)
