### ISSUE TITLE
error fail when OK

### ISSUE THREAD

**Issue by nicgirault** [theodo/scrumble#126]
Hello,

J'ai fait pile le bon nombre de points dans mon sprint mais j'ai le label "FAIL" est ce normal ?

**Comment by tychota** [comment]
Fixed by #140 (I find this issue only after, sorry :/ )
You may close this ;)

**Comment by tychota** [comment]
How is it deployed by the way ? Did you have to manually run the copy to gh-page or a webhook/ci do this automagically ?
