### ISSUE TITLE
Avoid authorizing Google every day

### ISSUE THREAD

**Issue by nicgirault** [theodo/scrumble#131]
We already fetch refresh token. We should use it and ping loopback api to see if user has gmail access or not instead of pinging google/userinfo

**Comment by tychota** [comment]
Avec : https://github.com/theodo/scrumble/blob/master/client/src/login/config/google.coffee#L12 il obtient déja un refresh_token qui peut être refresh.

Il faut de plus le paramètre prompt en force : http://stackoverflow.com/a/8942732. Ceci sert en cas de perte du token (exemple l'user vide son localstorage).

Il faut store le `exp = Date().now / 1000 | 0 + expired_in`dans le localstorage et check à la requète si `Date().now / 1000 | 0 < localstorage.exp`

Enfin, dans le service googleauth, si le token est unexpired, il faut faire un post:

````
POST /oauth2/v4/token HTTP/1.1
Host: www.googleapis.com
Content-Type: application/x-www-form-urlencoded

client_id=8819981768.apps.googleusercontent.com&
client_secret={client_secret}&
refresh_token=1/6BMfW9j53gdGImsiyUH5kU5RsR4zwI9lUVX-tqf8JXQ&
grant_type=refresh_token
````

cf https://developers.google.com/identity/protocols/OAuth2WebServer#offline

**Comment by nicgirault** [comment]
@tychota je pensais plutôt le stocker en bdd, non ? https://github.com/theodo/scrumble/blob/master/api/src/models/scrumble-user.coffee#L87

**Comment by tychota** [comment]
ça m'a l'air d'un anti pattern de sécurité assez grave:
- https://tools.ietf.org/html/rfc6819#section-5.1.4.1.3
- https://tools.ietf.org/html/rfc6819#section-4.3.2

Ca m' l'air encore plus galère avec les refreshtoken qui ont une durée illimité. A l'heure actuelle on ne passe pas un device id donc impossible de révoquer un token de facon sécure, je crois.

**Comment by nicgirault** [comment]
OK. Merci pour les refs
