### ISSUE TITLE
Changement de projet et Daily Mail

### ISSUE THREAD

**Issue by Nhacsam** [theodo/scrumble#185]
Quand j'ouvre la page "Write Today's Daily" et que je change ensuite de projet, quand je reviens sur la page, mon daily est toujours prérempli avec les informations de l'ancien projet.

**Comment by nicgirault** [comment]
Merci pour ton feedback @Nhacsam. J'avais déjà constaté ça. T'es chaud pour faire une PR ?

Il faut reset le cache lors du changement de projet. Le cache est ici https://github.com/theodo/scrumble/blob/master/client/src/daily-report/services/dailyCache.coffee.

Le changement de projet est ici : https://github.com/theodo/scrumble/blob/master/client/src/project/states/main/controller.coffee. ça mériterait largement d'être déplacé dans un service...

**Comment by Nhacsam** [comment]
Yes, je vais regarder. Si je vois que je galère ou que je n'ai pas le temps, je te fait signe.
