### ISSUE TITLE
Being late when we are exactly on the curve

### ISSUE THREAD

**Issue by Mx-Glitter** [theodo/scrumble#193]
Right now, Scrumble decides we are late when we are exactly on the curve, c.f. screenshot. It should decide we're ahead.
<img width="209" alt="screen shot 2016-08-08 at 10 02 06" src="https://cloud.githubusercontent.com/assets/4671739/17473200/7be55744-5d4f-11e6-98fa-b735c2f382e4.png">

**Comment by b-jan** [comment]
Solved
