### ISSUE TITLE
When I change my Trello email (or when I have 2) I can't see my boards anymore

### ISSUE THREAD

**Issue by JusteLeblanc** [theodo/scrumble#202]
- You can have multiple emails on Trello, only one Primary but you can change it
- You can change your username on Trello

Scrumble identifies user by email as there are still 48 users who don't have remoteId
![image](https://cloud.githubusercontent.com/assets/5615054/19310402/31140ac6-908a-11e6-97e1-a2990dd17344.png)

My advise is to reset users from Parse.

**Comment by nicgirault** [comment]
Pour reproduire > changer l'email par defaut de Trello
