### ISSUE TITLE
Blank BDC in daily emails

### ISSUE THREAD

**Issue by foucdeg** [theodo/scrumble#212]
In the email preview and actual email sent with Scrumble, the BDC image is completely white. 
This is systematic on some computers and not on others. 
@nicgirault I'm forwarding you my latest daily email. 

![image](https://cloud.githubusercontent.com/assets/12948989/24791129/40b492c8-1b79-11e7-8a52-b1760abfc893.png)

**Comment by foucdeg** [comment]
Before @nicgirault's latest update, I didn't. Now I still have the problem but don't know whether there's an error now. I'll check.

**Comment by foucdeg** [comment]
![image](https://cloud.githubusercontent.com/assets/12948989/24916696/27b5007c-1edb-11e7-8e53-f977eeaa4cb8.png)
Not sure if this is related

**Comment by nicgirault** [comment]
@foucdeg it's not related

**Comment by foucdeg** [comment]
@nicgirault Cmd-Shift-R fixed it :)
