### ISSUE TITLE
Can't connect to Scrumble because my username is already registered

### ISSUE THREAD

**Issue by Mx-Glitter** [theodo/scrumble#215]
When I click on Login with Trello, I have this error:

![image](https://user-images.githubusercontent.com/4671739/29271964-482d00d6-80fe-11e7-8705-66202c877152.png)

For the context, my Trello account was registered with another email address before when I was at Theodo. Now I have a new one at Sicara and the system doesn't recognize me. I recommand to wipe out my user in Scrumble database to even things out and start fresh but I don't have access to the server to do it mysel, help?

**Comment by Triiistan** [comment]
I managed to get in by changing my primary email to my personal one instead of Sicara's one for info.

**Comment by b-jan** [comment]
This bug has been solved !
