### ISSUE TITLE
Unable to connect or use scrumble

### ISSUE THREAD

**Issue by incepter** [theodo/scrumble#225]
All the scrumble calls return a 401, and the login returns a 422.
It's been a week for me, I cannot use scrumble in all my devices.

My trello account was linked to a corporate email (that i assume was deleted) but i changed my trello email adress to my personnal, i was removed from all the corporate boards, but i am still unable to use scrumble for my personnal use cases (project at home etc).

Could you please tell me what's the matter ? I have friends using scrumble with success..

**Comment by b-jan** [comment]
Sorry for that, this issue is now solved. You shoud be able to login again.
