### ISSUE TITLE
Bug when clicking "AUTHORIZE GMAIL"

### ISSUE THREAD

**Issue by Mx-Glitter** [theodo/scrumble#236]
Impact: I can't send the daily mail
![image](https://user-images.githubusercontent.com/4671739/44649252-a07cbd80-a9e3-11e8-98f1-11742b6b42de.png)

**Comment by Mx-Glitter** [comment]
@b-jan I guess this issue can be closed 😉. I let you do it yourself in case you want to do more with this issue.

**Comment by b-jan** [comment]
closed !! tahnk you :)
